### PR TITLE
Removing GridFieldOrderableRows as it is not listed as a composer dependency

### PR DESCRIPTION
**Pull request by jaedb**
- Resolves issue on SilverStripe 3.1.1

### CODE REVIEW

**Comment by xini** [comment]
That's not really the solution. I'd rather add it to composer.json (even though it doesn't work at the moment due to https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/issues/134)

**Comment by jaedb** [comment]
@xini Even better - just as long as it works! Do you know when this is likely to be resolved?

**Comment by xini** [comment]
no I don't.

**Comment by dhensby** [comment]
@jaedb it is listed in the composer.json as a dependency. What version are you using?

**Comment by dhensby** [comment]
Is this not a dupe of #87 ?

**Comment by jaedb** [comment]
Nope, these are two different concerns. This issue covers an issue with `SortableGridField`, #87 covers an issue with adding a link within the CMS' _Insert Link_ dialog.

**Comment by dhensby** [comment]
So why does this PR have the same commit as #87 in it?

I'm still waiting for a reply to my query:

> @jaedb it is listed in the composer.json as a dependency. What version are you using?

**Pull request closed without merging**
