### PR TITLE
fix edit after upload (from @benmanu), fixes #53

### LINKED ISSUE #53: Unable to edit file immediately after uploading
When attaching files to a page using the “AssetUploadField” view, if you click the “Edit” button after uploading you’ll get a server error:

> Argument 1 passed to UploadField::getFileEditFields() must be an instance of File, instance of DMSDocument given

I’m not sure if this can actually be fixed in this module. Screenshot attached of the view I’m referring to.

screen shot 2014-09-18 at 10 01 03

### PR DESCRIPTION
**Pull request by xini**
I have integrated the fix from https://github.com/benmanu/silverstripe-dms/commit/a5e2d29e9c80d7eea9f6825764c50b8ea360e9ca as mentioned in https://github.com/silverstripe/silverstripe-dms/issues/53#issuecomment-233222642

### CODE REVIEW

**Comment by dhensby** [comment]
Failed test. I've restarted. If it fails again, it'll need investigating

**Comment by xini** [comment]
can this be merged? cheers.

**Comment by dhensby** [comment]
Thanks :)

**Comment by xini** [comment]
Thank you!

**Comment by xini** [comment]
could you please tag a release with this?

**Comment by dhensby** [comment]
v1.3.0 released

**Comment by xini** [comment]
Thanks!

**Pull request merged**
